feat(auth): prompt to create local creds
ice-blockchain/ion-app pull request #468
Opened 2024-12-23 13:33 UTC by ice-tychon

## Description
This PR adds the ability for users to create local credentials after logging in using another device.

## Additional Notes
- Added `preferImmediatelyAvailableCredentials` param to login
- Added `CreateNewCredentialsService`
- Added `CreateLocalCredsPromptDialog`
- Updated redirect route logic

## Type of Change
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Refactoring
- [ ] Documentation
- [ ] Chore

## Screenshots (if applicable)

2024-12-23 15:24 UTC, ice-alcides approved these changes

2024-12-23 15:28 UTC, ice-ajax commented on lib/app/features/auth/views/pages/create_local_creds_prompt_dialog/create_local_creds_prompt_dialog.dart
> +    }
Shouldn't we let `go_router_provider` handle that redirect, as it is now?

2024-12-23 15:50 UTC, ice-ajax approved these changes

2024-12-23 16:21 UTC, ice-endymion requested changes

2024-12-23 16:21 UTC, ice-endymion commented on packages/ion_identity_client/lib/src/auth/dtos/create_credentials_response.c.g.dart
> +// GENERATED CODE - DO NOT MODIFY BY HAND
Do we commit generated files?

2024-12-23 19:33 UTC, ice-tychon commented on packages/ion_identity_client/lib/src/auth/dtos/create_credentials_response.c.g.dart
> +// GENERATED CODE - DO NOT MODIFY BY HAND
We do in packages/libraries.

2024-12-24 06:57 UTC, ice-kreios approved these changes

2024-12-24 08:03 UTC, ice-endymion approved these changes

2024-12-24 08:03 UTC, merged